### ISSUE TITLE
install roadrunner and meep meep

### ISSUE THREAD

**Issue by krachtr** [krachtr/FtcRobotController22-23#14]
- [x] path visualization using meep meep: [https://learnroadrunner.com/tool/meepmeep.html](url)
- [x] install roadrunner: [https://learnroadrunner.com/installing.html#method-2-installing-rr-on-your-project](url)
- [x] tuning: [https://learnroadrunner.com/feedforward-tuning.html](url)

**Comment by UC-Teresa** [comment]
Learn how to install and use
