### ISSUE TITLE
determine if you are likely to go to the march for life

### ISSUE THREAD

**Issue by krachtr** [krachtr/FtcRobotController22-23#7]
are you likely to go to the march for life? please answer under discussions

**Comment by monicarobots** [comment]
i do not think i will go to the march

**Comment by JosephUCRobotics** [comment]
i do not think i will go to the march

**Comment by BENGALABA** [comment]
I think I will

**Comment by monicarobots** [comment]
I looked at my email today and i had so many emails.

**Comment by marieeeeeeeeeeeeeeeeeee** [comment]
probably not
