### ISSUE TITLE
revise drive chassis

### ISSUE THREAD

**Issue by krachtr** [krachtr/FtcRobotController22-23#9]
### Discussed in https://github.com/krachtr/FtcRobotController22-23/discussions/8

<div type='discussions-op-text'>

<sup>Originally posted by **krachtr** September  6, 2023</sup>
What revisions are required to the onshape parts?</div>

**Comment by JosephUCRobotics** [comment]
this it the list i have
Think about removing the encoder pod and put the encoder on the wheel
Encoder pod block
Encoder pod gap width bigger
Modor mount screw holes bigger
Encoder on the outside of the pod and fill in the pod so the Encoder pod has motor support 
Spring hooks bigger
Open encoder back for the baring
Fix design so you can get shaft out easier
Motor set screw hole bigger
